spring.application.name=api-gateway

#user-services
spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8010
spring.cloud.gateway.mvc.routes[0].predicates=Path=/user/**

#payment-services
spring.cloud.gateway.mvc.routes[1].id=payment-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8011
spring.cloud.gateway.mvc.routes[1].predicates=Path=/payment/**
